# Application of TOPSIS method for partner selection


### What is TOPSIS?
The Technique for Order of Preference by Similarity to Ideal Solution (TOPSIS) is a multi-criteria decision analysis method, which was originally developed by Ching-Lai Hwang and Yoon in 1981 with further developments by Yoon in 1987, and Hwang, Lai and Liu in 1993. TOPSIS is based on the concept that the chosen alternative should have the shortest geometric distance from the positive ideal solution (PIS) and the longest geometric distance from the negative ideal solution (NIS).

### Description
It is a method of compensatory aggregation that compares a set of alternatives by identifying weights for each criterion, normalising scores for each criterion and calculating the geometric distance between each alternative and the ideal alternative, which is the best score in each criterion. An assumption of TOPSIS is that the criteria are monotonically increasing or decreasing. Normalisation is usually required as the parameters or criteria are often of incongruous dimensions in multi-criteria problems. Compensatory methods such as TOPSIS allow trade-offs between criteria, where a poor result in one criterion can be negated by a good result in another criterion. This provides a more realistic form of modelling than non-compensatory methods, which include or exclude alternative solutions based on hard cut-offs.

More info: https://en.wikipedia.org/wiki/TOPSIS#cite_note-indjst.org-4

TOPSIS calcultator example: https://decision-radar.com/Topsis.html

### Definition of a Class Company

This class represent a company and have the parameters that we're going to use in our TOPSIS analysis, wich are:
- Quality
- Price
- Support
- User community
- Reliability

In [1]:
import numpy as np

In [2]:
class Company:
    def __init__(self,name,quality=0,support=0,user_com=0,reliability=0):
        self.name = name
        self.quality = quality
        self.support = support
        self.user_com = user_com
        self.reliability = reliability

    def give_name(self):
        return self.name
    
    def give_quality(self):
        return self.quality
    
    def give_support(self):
        return self.support
    
    def give_user_com(self):
        return self.user_com

    def give_reliability(self):
        return self.reliability

In [3]:
#initializing some companys to work with an example:

company1 = Company('google',quality=8,support=7,user_com=10,reliability=7)
company2 = Company('azure',quality=7,support=7,user_com=9,reliability=7)
company3 = Company('amazon',quality=8,support=8,user_com=10,reliability=8)
company4 = Company('ibm',quality=9,support=9,user_com=8,reliability=9)
company5 = Company('oracle',quality=7,support=8,user_com=8,reliability=7)

We have to distribute the weights for our parameters:

In [4]:
dict_parameters = {'quality':0.25,'support':0.15,'user_com':0.2,'reliability':0.3}
params_list = [dict_parameters['quality'],dict_parameters['support'],
               dict_parameters['user_com'],dict_parameters['reliability']]

### Step 1: Normalization

In [5]:
#list of companies:
list_of_comps = []
list_of_comps.append(company1); list_of_comps.append(company2)
list_of_comps.append(company3);list_of_comps.append(company4);list_of_comps.append(company5)

topsis_matrix = np.array
topsis_matrix = []
row = []
for company in list_of_comps :
    row.append(company.give_quality())
    row.append(company.give_support())
    row.append(company.give_user_com())
    row.append(company.give_reliability())
    topsis_matrix = np.append(topsis_matrix,row)
    row.clear()
    
topsis_matrix = topsis_matrix.reshape(5,4)
print(topsis_matrix)

#something like this 
 #[['Company' 'Quality' 'Support' 'User Community' 'Reliability']
 #['google'     '8'       '7'         '10'             '7']
 #['azure'      '7'       '7'         '9'              '7']
 #['amazon'     '8'       '8'         '10'             '8']
 #['ibm'        '9'       '9'         '8'              '9']
 #['oracle'     '7'       '8'         '8'              '7']]


[[ 8.  7. 10.  7.]
 [ 7.  7.  9.  7.]
 [ 8.  8. 10.  8.]
 [ 9.  9.  8.  9.]
 [ 7.  8.  8.  7.]]


As you can see, we don't have the normal matrix just yet! Let's normalize it.

In [6]:
topsis_matrix_norm = topsis_matrix / topsis_matrix.sum(axis=0)
print(topsis_matrix_norm)

[[0.20512821 0.17948718 0.22222222 0.18421053]
 [0.17948718 0.17948718 0.2        0.18421053]
 [0.20512821 0.20512821 0.22222222 0.21052632]
 [0.23076923 0.23076923 0.17777778 0.23684211]
 [0.17948718 0.20512821 0.17777778 0.18421053]]


### Step 2: Consider weights

In [29]:
topsis_matrix_norm_weighted = np.array
topsis_matrix_norm_weighted = []

i=0
while (i < topsis_matrix_norm.shape[0]-1):
    topsis_matrix_norm_weighted = np.append(topsis_matrix_norm_weighted,topsis_matrix_norm[:,i]*params_list[i])
    i=i+1

topsis_matrix_norm_weighted = topsis_matrix_norm_weighted.reshape(5,4)
print(topsis_matrix_norm_weighted)

[[0.05128205 0.04487179 0.05128205 0.05769231]
 [0.04487179 0.02692308 0.02692308 0.03076923]
 [0.03461538 0.03076923 0.04444444 0.04      ]
 [0.04444444 0.03555556 0.03555556 0.05526316]
 [0.05526316 0.06315789 0.07105263 0.05526316]]


### Step 3a: Determine ideal positive solution

In [8]:
ideal_positive_sol = np.array
ideal_positive_sol = []

ideal_positive_sol = topsis_matrix_norm_weighted.max(axis=0)
print (ideal_positive_sol)

[0.05526316 0.06315789 0.07105263 0.05769231]


### Step 3b: Determine ideal negative solution

In [28]:
ideal_negative_sol = np.array
ideal_negative_sol = []

ideal_negative_sol = topsis_matrix_norm_weighted.min(axis=0)
print (ideal_negative_sol)

[0.03461538 0.02692308 0.02692308 0.03076923]


### Step 4a: Determine separation from ideal solution

In [41]:
ideal_positive_mat = np.array
ideal_positive_mat = []

i=0
while (i < topsis_matrix_norm_weighted.shape[0]-1):
    ideal_positive_mat = np.append( ideal_positive_mat, (topsis_matrix_norm_weighted[:,i]-ideal_positive_sol[i])**2 )
    i = i+1

ideal_positive_mat = ideal_positive_mat.reshape(5,4)
print(ideal_positive_mat)

[[1.58492099e-05 1.07980425e-04 4.26330541e-04 1.17044561e-04]
 [0.00000000e+00 3.34381448e-04 1.31296202e-03 1.04902555e-03]
 [7.61889128e-04 0.00000000e+00 3.90875845e-04 1.94741759e-03]
 [7.07995623e-04 1.26004241e-03 0.00000000e+00 0.00000000e+00]
 [7.24852071e-04 3.13017751e-04 5.90076874e-06 5.90076874e-06]]


And the sum for each company:

In [51]:
from numpy import sqrt
sum_pos = np.array
sum_pos = sqrt(np.sum(ideal_positive_mat,axis=1))
sum_pos = sum_pos.reshape(5,1)
print(sum_pos)

[[0.02583031]
 [0.05192657]
 [0.05567928]
 [0.04436257]
 [0.03239863]]


### Step 4b: Determine separation from negative ideal solution

In [39]:
ideal_negative_matrix = np.array
ideal_negative_matrix = []

i=0
while (i < topsis_matrix_norm_weighted.shape[0]-1):
    ideal_negative_matrix = np.append( ideal_negative_matrix, (topsis_matrix_norm_weighted[:,i]-ideal_negative_sol[i])**2 )
    i = i+1

ideal_negative_matrix = ideal_negative_matrix.reshape(5,4)
print(ideal_negative_matrix)

[[2.77777778e-04 1.05193951e-04 0.00000000e+00 9.66104171e-05]
 [4.26330541e-04 3.22156476e-04 0.00000000e+00 1.47928994e-05]
 [7.45196873e-05 1.31296202e-03 5.93359632e-04 0.00000000e+00]
 [3.06998320e-04 7.45196873e-05 1.94741759e-03 7.24852071e-04]
 [0.00000000e+00 8.52071006e-05 5.99952466e-04 5.99952466e-04]]


In [52]:
from numpy import sqrt
sum_neg = np.array
sum_neg = sqrt(np.sum(ideal_negative_matrix,axis=1))
sum_neg = sum_neg.reshape(5,1)
print(sum_)

[[0.02583031]
 [0.05192657]
 [0.05567928]
 [0.04436257]
 [0.03239863]]


### Step 5: Calculate the relative closeness to the ideal solution 

In [58]:
sol_matrix = np.array

sol_matrix = sum_neg / (sum_neg + sum_pos)

sol_matrix = sol_matrix.reshape(5,1)
print(sol_matrix)
print("Best score: {}".format(sol_matrix.max()))

[[0.45882077]
 [0.34727969]
 [0.44424048]
 [0.55469841]
 [0.52527454]]
Best score: 0.5546984103098137


#### So we can conclude that our best potential partner is:

In [60]:
print(list_of_comps[3].give_name())

ibm


## Conclusion

As we can see this is a super easy to understand and basic example of TOPSIS method using Python!
However, we could easily make an application with all the methods used and generalize it to make a real partner calculator!